//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial1.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Computador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Computador()
        {
            this.Ventas = new HashSet<Venta>();
        }
    
        public int ComputadorID { get; set; }
        public int TipoComputadorID { get; set; }
        public int Procesadores { get; set; }
        public string MarcaProcesador { get; set; }
        public string DiscoDuro { get; set; }
        public string MemoriaRAM { get; set; }
        public string Componentes { get; set; }
        [JsonIgnore]
        public virtual TipoComputador TipoComputador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Venta> Ventas { get; set; }


    }
}
